esphome:
  name: coffe-machine
  friendly_name: Coffe Machine

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<ENCRYPTION_KEY_HERE>"

ota:
  - platform: esphome
    password: "<OTA_PASSWORD_HERE>"

# Variables
globals:
  # Maitenance flag (persistent)
   - id: maitenance_flag
     type: int
     restore_value: true
     initial_value: '0'
  # State flag
  # 0 -> Off
  # 1 -> HEATING_UP
  # 2 -> READY
  # 3 -> COFFE
   - id: state_flag
     type: int
     initial_value: '0'

text_sensor:
  - platform: template
    name: "Status"
    icon: "mdi:state-machine"
    update_interval: 0.05s
    lambda: |-
      if (id(state_flag) == 0) {
        id(led_heating).turn_off();
        id(led_ready).turn_off();

        return {"Off"};
      } else if (id(state_flag) == 1) {
        id(led_heating).turn_on();
        id(led_ready).turn_off();

        return {"Heating Up"};
      } else if (id(state_flag) == 2) {
        id(led_heating).turn_off();
        id(led_ready).turn_on();

        return {"Ready"};
      } else if (id(state_flag) == 3) {
        id(led_heating).turn_on();
        id(led_ready).turn_on();

        return {"Coffe"};
      }

      return {"Unknown"};



button:
  # Power button
  - platform: template
    name: "Power On/Off"
    id: power_button
    icon: "mdi:power-cycle"
    on_press:
        then:
          - switch.turn_off: coffe_relay
          - switch.turn_on: power_relay
          - delay: 0.5s
          - switch.turn_off: power_relay
          - lambda: |-
              // Check if state is off
              if (id(state_flag) == 0) {
                // Move to Heating up
                id(state_flag) = 1;
              } else {
                // Turn off
                id(state_flag) = 0;
              }
          
  # Start Maintenance
  - platform: template
    name: "Maintenance Mode"
    id: maintenance_button
    icon: "mdi:wrench"
    on_press:
        then:
          - switch.turn_off: coffe_relay
          - switch.turn_on: power_relay
          - delay: 8s
          - switch.turn_off: power_relay
  # Coffe (Short)
  - platform: template
    name: "Expresso (Short)"
    id: short_coffe_button
    icon: "mdi:size-s"
    on_press:
        - if:
            condition:
               switch.is_on: led_ready
            then:
              - switch.turn_on: coffe_relay
              - delay: 12s
              - switch.turn_off: coffe_relay
  # Coffe (Medium)
  - platform: template
    name: "Expresso (Long)"
    id: medium_coffe_button
    icon: "mdi:size-m"
    on_press:
        - if:
            condition:
               switch.is_on: led_ready
            then:
              - switch.turn_on: coffe_relay
              - delay: 16s
              - switch.turn_off: coffe_relay
  # Coffe (Long)
  - platform: template
    name: "Coffe (Long)"
    id: large_coffe_button
    icon: "mdi:size-xxl"
    on_press:
      - if:
          condition:
              switch.is_on: led_ready
          then:
            - switch.turn_on: coffe_relay
            - delay: 32s
            - switch.turn_off: coffe_relay

switch:
  # Power Relay
  - platform: gpio
    name: "Power On/Off"
    id: power_relay
    internal: true
    icon: "mdi:power-cycle"
    pin:
      number: D1
      inverted: true
  # Coffe Relay
  - platform: gpio
    icon: "mdi:coffee"
    id: coffe_relay
    internal: false
    name: "Coffe"
    pin:
      number: D2
      inverted: true
    on_turn_on: 
      then:
        - lambda: |-
            // If machine is "READY" move to "COFFE"
            if (id(state_flag) == 2) {
              id(state_flag) = 3;
            } else {
              // If machine is not in "READY" state reset relay
              id(coffe_relay).turn_off();
            }
    on_turn_off: 
      then:
        - lambda: |-
            // If machine was in "COFFE" move to "HEATING_UP"
            if (id(state_flag) == 3) {
              id(state_flag) = 1;
            }

  # Heating LED (RGB) (Output)
  - platform: gpio
    name: "Heating LED"
    internal: true
    pin: 
      number: D8
    id: led_heating
  # Ready LED (Output)
  - platform: gpio
    name: "Ready LED"
    internal: true
    pin: 
      number: D4
    id: led_ready
            

binary_sensor:
  # Ready indicator (Input, Green LED)
  - platform: gpio
    name: "Ready"
    id: green_led
    icon: "mdi:coffee-maker-check"
    internal: false
    pin:
      number: D5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: 20ms
      - delayed_off: 20ms
    on_press: 
      then:
        lambda: |-
          // If state was "HEATING_UP" or "COFFE" move to "READY" 
          id(state_flag) = 2;
    on_release: 
      then:
        lambda: |-
          // If state was "READY" the machine has turned off automatically
          if (id(state_flag) == 2) {
            id(state_flag) = 0;
          }

  # Heating Up (Input, Red LED)
  - platform: gpio
    name: "Heating Up"
    id: red_led
    icon: "mdi:thermometer-plus"
    pin:
      number: D6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms

  # Maintenance Flag 
  - platform: template
    name: "Maintenance"
    icon: "mdi:alert-circle"
    device_class: problem
    lambda: |-
      // If both red and green are on the machine needs maintenance
      if (id(red_led).state && id(green_led).state) {
        id(maitenance_flag) = 1;
        return true;
      } else {
        // If only green is turned on reset maitenance
        if (id(green_led).state) {
          id(maitenance_flag) = 0;
        }
        
        return id(maitenance_flag) == 1;
      }
  
  # Power Physical Button
  - platform: gpio
    name: "Power Button"
    internal: true
    id: user_power_button
    pin:
      number: D7
      mode:
        input: true
        pullup: true
      inverted: True
    filters:
      - delayed_off: 100ms
    on_press: 
      then:
        - button.press: power_button

  # Coffe Physical Button
  - platform: gpio
    name: "Coffe Button"
    internal: true
    id: user_button
    pin:
      number: D3
      mode:
        input: true
        pullup: true
      inverted: False
    filters:
      - delayed_off: 100ms
    on_multi_click:
        - timing:
             - ON for at most 1s
             - OFF for at least 0.2s
          then:
              - if:
                  condition:
                    switch.is_on: coffe_relay
                  then:
                    - switch.turn_off: coffe_relay
                  else:
                    - button.press: short_coffe_button
        - timing:
             - ON for at least 1.2s
          then:
            - if:
                condition:
                    switch.is_on: coffe_relay
                then:
                  - switch.turn_off: coffe_relay
                else:
                  - button.press: large_coffe_button

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
